# Dalux Build API - Complete Demo

## Setup: Configure API Client

In [1]:
!uv add pandas --active -q

In [2]:
# Add local package to path
import sys
from pathlib import Path

project_root = Path.cwd()
python_dir = project_root / "python"

if str(python_dir) not in sys.path:
    sys.path.insert(0, str(python_dir))
    print(f"✓ Added {python_dir} to Python path")

import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

BASE_URL = os.getenv("DALUX_BASE_URL")
API_KEY = os.getenv("DALUX_API_KEY")

if BASE_URL and API_KEY:
    print(f"✓ API credentials loaded from environment")
else:
    print(f"⚠️  Set DALUX_BASE_URL and DALUX_API_KEY environment variables")

✓ Added /Users/brunoadam/Documents/development/github/dalux-build/python/notebooks/python to Python path
✓ API credentials loaded from environment

In [3]:
# Create Dalux client with Pydantic support
from dalux_build import create_client

dalux = create_client()

In [4]:
import dalux_build
dalux_build.__version__

'2.1.4'

In [5]:
projects = dalux.projects.list_projects()

/var/folders/d1/x6l5g3q17xl7sxts9r454k6r0000gn/T/ipykernel_6966/3877746552.py:1: DeprecationWarning: list_projects() is deprecated and only returns the first page of results. Use get_projects() instead to fetch all projects with pagination.
  projects = dalux.projects.list_projects()

In [6]:
if len(projects) == 0:
    print("⚠️  No projects found for the current user")
    raise SystemExit("Please check your API credentials and try again.")
elif len(projects) == 1:
    print(f"✓ Found 1 project: {projects[0].project_name}")
    PROJECT_ID = projects[0].project_id
    dalux.set_default_project(PROJECT_ID)
else:
    PROJECT_ID = os.getenv("DALUX_PROJECT_ID")
    dalux.set_default_project(PROJECT_ID)

print(f"✓ Using project ID: {PROJECT_ID}")

✓ Found 1 project: LLYN.B250_GMP-Facility – Turnkey Contractor
✓ Using project ID: S313578016888324096

In [7]:
file_areas = dalux.file_areas.get_file_areas()
file_areas

[FileArea(file_area_id='S313578021116182528', file_area_name='Files', file_area_type='files'),
 FileArea(file_area_id='S313578021132959744', file_area_name='Shared files', file_area_type='shared'),
 FileArea(file_area_id='S313578021149736960', file_area_name='Published files', file_area_type='published')]

In [12]:
# Use the correct path: Files/Files/4_Design/...
all_files = dalux.files.get_files_in_folder(
    path="Files/4_Design/C07_Geometry/C07.01_Drawing/K01_Architecture",
    verbose=True,
    subfolders=True,
    to_dataframe=True
)
print(f"\n✓ Found {len(all_files)} files")
all_files

GET /5.1/projects/S313578016888324096/file_areas
GET /5.1/projects/S313578016888324096/file_areas/S313578021116182528/folders

Fetching pages: 100%|██████████| 1936/1936 [00:01<00:00, 1574.26item/s]

Auto-navigating into 'Files' folder (ID: S313578021070045184)
GET /6.1/projects/S313578016888324096/file_areas/S313578021116182528/files params={'includeProperties': True}

Fetching pages: 100%|██████████| 5138/5138 [00:15<00:00, 338.10item/s]

Files matching folder 'S318295287208607744': 206

✓ Found 206 files

,fileId,fileRevisionId,fileName,fileAreaId,folderId,uploadedByUserId,uploaded,lastModifiedByUserId,lastModified,version,...,last_modified_by_user::lastName,last_modified_by_user::companyId,last_modified_by_user::company::companyId,last_modified_by_user::company::name,last_modified_by_user::company::vatNumber,last_modified_by_user::company::address,last_modified_by_user::company::city,last_modified_by_user::company::postalCode,last_modified_by_user::company::country,last_modified_by_user::company::catalogCompanyId
0,S452728037096554500,S452728288884817920,LLYN.B250_K01_T99_H5_EX_N400.pdf,S313578021116182528,S452084140108414976,1034258_1lVraZXxPEd4gttV,2026-06-03,822772_JzPTIUMA1MLdIETC,2026-07-14,1,...,Holban,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
1,S361097234864930820,S453101834001711105,LLYN.B250_K01_T32_H6_EX_N611.pdf,S313578021116182528,S404982828468535296,822772_JzPTIUMA1MLdIETC,2026-01-08,584864_uRauNc9zbqtABZb4,2026-06-04,4,...,Lillebæk,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
2,S364707333944639492,S453101834001711107,LLYN.B250_K01_T99_H5_EX_N400.pdf,S313578021116182528,S404982828468535296,822772_JzPTIUMA1MLdIETC,2026-02-27,584864_uRauNc9zbqtABZb4,2026-06-04,5,...,Lillebæk,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
3,S363674755800236032,S457917032050982914,LLYN.B250_K01_T99_H1_ET_N158.pdf,S313578021116182528,S405334989962477568,822772_JzPTIUMA1MLdIETC,2026-06-04,640149_cQTJBp9rfgFwyhng,2026-06-16,14,...,Davies,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
4,S363674757696061442,S457917032050982917,LLYN.B250_K01_T99_H1_ET_N159.pdf,S313578021116182528,S405334989962477568,822772_JzPTIUMA1MLdIETC,2026-06-15,640149_cQTJBp9rfgFwyhng,2026-07-14,15,...,Davies,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,S363665883337326596,S479969071983493122,LLYN.B250_K01_T22_H1_EK_N101.pdf,S313578021116182528,S339020196205297664,1034258_1lVraZXxPEd4gttV,2026-08-17,1034258_1lVraZXxPEd4gttV,2026-08-17,16,...,Lorentzen,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
202,S440821011751895045,S479969071983493125,LLYN.B250_K01_T99_H4_ET_N423.pdf,S313578021116182528,S339019850292658176,1034258_1lVraZXxPEd4gttV,2026-08-17,1034258_1lVraZXxPEd4gttV,2026-08-17,6,...,Lorentzen,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
203,S474905516494028804,S479969071983493128,LLYN.B250_K01_T22_H4_ES_N490.pdf,S313578021116182528,S474905152831094784,1034258_1lVraZXxPEd4gttV,2026-08-17,1034258_1lVraZXxPEd4gttV,2026-08-17,3,...,Lorentzen,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
204,S364707186405801988,S479975711776440323,LLYN.B250_K01_T99_H5_EX_N300.pdf,S313578021116182528,S363785476458414080,1034258_1lVraZXxPEd4gttV,2026-08-17,1034258_1lVraZXxPEd4gttV,2026-08-17,15,...,Lorentzen,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
205,S364706844066709508,S479975870497292291,LLYN.B250_K01_T99_H5_EX_N200.pdf,S313578021116182528,S339019508385579008,1034258_1lVraZXxPEd4gttV,2026-08-17,1034258_1lVraZXxPEd4gttV,2026-08-17,21,...,Lorentzen,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None

In [14]:
# Filters the files that are "drawing" as file_type

selected_files_df = all_files[all_files["fileType"] == "drawing"]

In [18]:
selected_files_df

,fileId,fileRevisionId,fileName,fileAreaId,folderId,uploadedByUserId,uploaded,lastModifiedByUserId,lastModified,version,...,last_modified_by_user::lastName,last_modified_by_user::companyId,last_modified_by_user::company::companyId,last_modified_by_user::company::name,last_modified_by_user::company::vatNumber,last_modified_by_user::company::address,last_modified_by_user::company::city,last_modified_by_user::company::postalCode,last_modified_by_user::company::country,last_modified_by_user::company::catalogCompanyId
3,S363674755800236032,S457917032050982914,LLYN.B250_K01_T99_H1_ET_N158.pdf,S313578021116182528,S405334989962477568,822772_JzPTIUMA1MLdIETC,2026-06-04,640149_cQTJBp9rfgFwyhng,2026-06-16,14,...,Davies,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
4,S363674757696061442,S457917032050982917,LLYN.B250_K01_T99_H1_ET_N159.pdf,S313578021116182528,S405334989962477568,822772_JzPTIUMA1MLdIETC,2026-06-15,640149_cQTJBp9rfgFwyhng,2026-07-14,15,...,Davies,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
5,S454534603332386820,S464775966258888705,LLYN.B250_K01_T22_H1_ES_A001.pdf,S313578021116182528,S454529238326837248,822772_JzPTIUMA1MLdIETC,2026-06-29,1800285_U8gRHLPlVgk8Fp9P,2026-06-29,4,...,Adam,S323760581427331072,S323760581427331072,Aarsleff,,,None,None,None,None
6,S458170194792022020,S464775966258888707,LLYN.B250_K01_T22_H1_E1_A002.pdf,S313578021116182528,S454529238326837248,822772_JzPTIUMA1MLdIETC,2026-06-29,1800285_U8gRHLPlVgk8Fp9P,2026-06-29,2,...,Adam,S323760581427331072,S323760581427331072,Aarsleff,,,None,None,None,None
7,S462149028142907396,S464775966258888708,LLYN.B250_K01_T22_H1_E2_A003.pdf,S313578021116182528,S454529238326837248,822772_JzPTIUMA1MLdIETC,2026-06-29,1800285_U8gRHLPlVgk8Fp9P,2026-06-29,1,...,Adam,S323760581427331072,S323760581427331072,Aarsleff,,,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,S349484652018270211,S479969062584057862,LLYN.B250_K01_T35_H1_E2_N108.pdf,S313578021116182528,S339020250584449024,1034258_1lVraZXxPEd4gttV,2026-08-17,1034258_1lVraZXxPEd4gttV,2026-08-17,15,...,Lorentzen,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
200,S349484652018270216,S479969062584057865,LLYN.B250_K01_T35_H1_E1_N107.pdf,S313578021116182528,S339020250584449024,1034258_1lVraZXxPEd4gttV,2026-08-17,1034258_1lVraZXxPEd4gttV,2026-08-17,14,...,Lorentzen,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
201,S363665883337326596,S479969071983493122,LLYN.B250_K01_T22_H1_EK_N101.pdf,S313578021116182528,S339020196205297664,1034258_1lVraZXxPEd4gttV,2026-08-17,1034258_1lVraZXxPEd4gttV,2026-08-17,16,...,Lorentzen,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
202,S440821011751895045,S479969071983493125,LLYN.B250_K01_T99_H4_ET_N423.pdf,S313578021116182528,S339019850292658176,1034258_1lVraZXxPEd4gttV,2026-08-17,1034258_1lVraZXxPEd4gttV,2026-08-17,6,...,Lorentzen,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
203,S474905516494028804,S479969071983493128,LLYN.B250_K01_T22_H4_ES_N490.pdf,S313578021116182528,S474905152831094784,1034258_1lVraZXxPEd4gttV,2026-08-17,1034258_1lVraZXxPEd4gttV,2026-08-17,3,...,Lorentzen,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None

In [20]:
selected_files_df.head(5)

,fileId,fileRevisionId,fileName,fileAreaId,folderId,uploadedByUserId,uploaded,lastModifiedByUserId,lastModified,version,...,last_modified_by_user::lastName,last_modified_by_user::companyId,last_modified_by_user::company::companyId,last_modified_by_user::company::name,last_modified_by_user::company::vatNumber,last_modified_by_user::company::address,last_modified_by_user::company::city,last_modified_by_user::company::postalCode,last_modified_by_user::company::country,last_modified_by_user::company::catalogCompanyId
3,S363674755800236032,S457917032050982914,LLYN.B250_K01_T99_H1_ET_N158.pdf,S313578021116182528,S405334989962477568,822772_JzPTIUMA1MLdIETC,2026-06-04,640149_cQTJBp9rfgFwyhng,2026-06-16,14,...,Davies,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
4,S363674757696061442,S457917032050982917,LLYN.B250_K01_T99_H1_ET_N159.pdf,S313578021116182528,S405334989962477568,822772_JzPTIUMA1MLdIETC,2026-06-15,640149_cQTJBp9rfgFwyhng,2026-07-14,15,...,Davies,S324143729399037962,S324143729399037962,PLH,,,None,None,None,None
5,S454534603332386820,S464775966258888705,LLYN.B250_K01_T22_H1_ES_A001.pdf,S313578021116182528,S454529238326837248,822772_JzPTIUMA1MLdIETC,2026-06-29,1800285_U8gRHLPlVgk8Fp9P,2026-06-29,4,...,Adam,S323760581427331072,S323760581427331072,Aarsleff,,,None,None,None,None
6,S458170194792022020,S464775966258888707,LLYN.B250_K01_T22_H1_E1_A002.pdf,S313578021116182528,S454529238326837248,822772_JzPTIUMA1MLdIETC,2026-06-29,1800285_U8gRHLPlVgk8Fp9P,2026-06-29,2,...,Adam,S323760581427331072,S323760581427331072,Aarsleff,,,None,None,None,None
7,S462149028142907396,S464775966258888708,LLYN.B250_K01_T22_H1_E2_A003.pdf,S313578021116182528,S454529238326837248,822772_JzPTIUMA1MLdIETC,2026-06-29,1800285_U8gRHLPlVgk8Fp9P,2026-06-29,1,...,Adam,S323760581427331072,S323760581427331072,Aarsleff,,,None,None,None,None

In [22]:
dalux.set_default_file_area(file_areas[0].file_area_id)

In [23]:
file = dalux.files.get_file(file_id="S363674755800236032")

In [25]:
file

FileResponse(data=File(file_id='S363674755800236032', file_revision_id='S457917032050982914', file_name='LLYN.B250_K01_T99_H1_ET_N158.pdf', file_area_id='S313578021116182528', folder_id='S405334989962477568', uploaded_by_user_id='822772_JzPTIUMA1MLdIETC', uploaded_by_user=None, uploaded=datetime.date(2026, 6, 4), last_modified_by_user_id='640149_cQTJBp9rfgFwyhng', last_modified_by_user=None, last_modified=datetime.date(2026, 6, 17), version='14', deleted=False, file_type='drawing', file_size=3699026, content_hash='VIPev7b-at6f0ia8GHNShSrKV2lYW8zr_ylyjtuf6mw.pdf', download_link='https://node1.field.dalux.com/service/api/2.0/projects/S313578016888324096/file_areas/S313578021116182528/files/S363674755800236032/revisions/S457917032050982914/content', properties=[FilePropertyField(key='S313578074715193368', name='Status', values=[{'reference': {'key': '', 'value': 'Current'}}]), FilePropertyField(key='S313578074715193404', name='Content description', values=[{'text': 'Tagplan, ET'}]), FilePropertyField(key='S313578074715193406', name='Campus (L)', values=[{'reference': {'key': '0_1', 'value': 'LLYN'}}]), FilePropertyField(key='S318298975209783296', name='Bygværk (B)', values=[{'reference': {'key': '0_1', 'value': 'B250'}}]), FilePropertyField(key='S313578074715193410', name='Vidensområde (K)', values=[{'reference': {'key': '29170055_1', 'value': 'K01'}}]), FilePropertyField(key='S313578074715193412', name='Tema (T)', values=[{'reference': {'key': '366560056340119565_1', 'value': 'T99'}}]), FilePropertyField(key='S313578074715193416', name='Afbildningstype (H)', values=[{'reference': {'key': '29170082_1', 'value': 'H1'}}]), FilePropertyField(key='S313578074715193418', name='Etage (E)', values=[{'reference': {'key': '29170063_13', 'value': 'ET'}}]), FilePropertyField(key='S313578074715193414', name='Filtype (F)', values=[{'reference': {'key': '0_1', 'value': 'F01'}}]), FilePropertyField(key='S313578074715193360', name='File format', values=[{'text': 'pdf'}]), FilePropertyField(key='S313578074715193366', name='Number', values=[{'text': 'LLYN.B250_K01_T99_H1_ET_N158'}]), FilePropertyField(key='S313578074715193370', name='Title', values=[{'text': 'LLYN.B250_K01_T99_H1_ET_N158'}]), FilePropertyField(key='S313578074715193372', name='Scale', values=[{'text': '75'}])], saved_file_path=None, saved_metadata_path=None), links=[Link(rel='self', href='https://node1.field.dalux.com/service/api/5.0/projects/S313578016888324096/file_areas/S313578021116182528/files/S363674755800236032', method='GET'), Link(rel='deepLink', href='https://node1.field.dalux.com/service/api/projects/S313578016888324096/file_areas/S313578021116182528/files/S363674755800236032/revisions/S457917032050982914/deepLink', method='GET')])

In [27]:
from IPython.display import display, Markdown

display(Markdown(
    file.data.ask("What is the revision number of this file and the release date?")
))

📄 Extracting text from PDF using Mistral OCR...
✓ Text extracted from 1 pages (6850 chars)

Based on the extracted content from the **LLYN.B250_K01_T99_H1_ET_N158.pdf** file:

- The **revision table** shows that all entries are labeled **"REVISIONS"** (without specific revision details filled in).
- The **date column** consistently shows **"2017"** for all entries.
- The **"Issued For Construction"** note at the top suggests this is the **final approved version** for construction, but the revision number is not explicitly stated in the visible content.

### Likely Interpretation:
1. **Revision Number**:
   - Since no specific revision (e.g., "Rev. A", "Rev. 0") is listed, this is likely the **initial release (Rev. 0 or "Issued For Construction" baseline)**.
   - The file may be the first approved version, with the revision table reserved for future updates.

2. **Release Date**:
   - The date **"2017"** in the revision table likely indicates the **year of issuance** (possibly the month/day is missing or in another part of the document not shown in the images).

### Recommendation:
- Check the **title block** (usually in `img-0.jpeg` or `img-1.jpeg`) for:
  - A **revision number** (e.g., "Rev. 0", "IFC").
  - A **full date** (e.g., "DD-MMM-YYYY").
- If no revision is specified, assume this is **Revision 0** (initial release) with a **2017 issuance date**.

In [19]:
# Download from url of the first 5 files in the dataframe
for index, row in selected_files_df.head(5).iterrows():
    file_id = row["fileId"]
    file_name = row["fileName"]
    download_url = dalux.files.download_file_from_link(row["downloadLink"], file_name, save_path="downloads")

In [12]:
from IPython.display import display, Markdown

display(Markdown(
    dalux.ai.files.ask("Who uploaded the files and when?", data=all_files)
))

**Files were uploaded by:**
- **Maria Herreros** (email: mhd@ramboll.dk) on **June 10, 2025**.

**Last modified by:**
- **Barbora Bohacova** (email: bba@ramboll.dk) on **July 2, 2025**.

In [ ]:
version_sets = dalux.version_sets.get_version_sets(to_dataframe=True)
version_sets

In [ ]:
from dalux_build.models import FileNameFilter

filters = FileNameFilter(
    extensions=["ifc"],
    contains=["A valid string to filter files by name here"],
)

downloaded_files = dalux.version_sets.download_files(
    identifiers=[filters],
    version_set_ids=["a valid version_set_id here"], # You need to provide a valid version_set_id
    save_path="downloads",
    verbose=True
)
downloaded_files

In [ ]:
# Get the list of versions sets and their files
version_sets = dalux.version_sets.get_version_sets(to_dataframe=True)

version_set_ids = version_sets["versionSetId"].tolist()
version_set_ids

In [ ]:
downloaded_files = dalux.version_sets.download_files(
    identifiers=[filters],
    version_set_ids=version_set_ids,
    save_path="downloads",
    verbose=True
)
downloaded_files

In [ ]:
version_set_files = dalux.version_sets.list_version_set_files(
    version_set_id="a valid version_set_id here"
)
version_set_files

In [ ]:
project_tasks = dalux.tasks.get_all_project_tasks()
project_tasks

In [ ]:
# File area is resolved automatically from path
# If path starts with file area name that matches a root folder, auto-navigate into it
all_files_in_folder = dalux.files.get_files_in_folder(
    path="Files/4_Design/C07_Geometry/C07.05_BIM",
    verbose=True
)
print(f"\n✓ Found {len(all_files_in_folder)} files")
all_files_in_folder

In [ ]:
# Use the correct path: Files/Files/4_Design/...
all_files_in_folder = dalux.files.get_files_in_folder(
    path="Files/Files/4_Design/C07_Geometry/C07.05_BIM",
    verbose=True
)
print(f"\n✓ Found {len(all_files_in_folder)} files")
all_files_in_folder

In [ ]:
all_files_in_folder = dalux.files.get_all_files_in_folder(
    path="Files/4_Design/C07_Geometry/C07.05_BIM"
)
all_files_in_folder

In [ ]:
# Debug: Check folder IDs and hierarchy
def get_folder_info(folder):
    data = folder if isinstance(folder, dict) else folder.model_dump(by_alias=True)
    data = data.get("data", data)
    folder_id = data.get("folderId") or data.get("id")
    name = data.get("folderName") or data.get("name")
    parent_id = data.get("parentFolderId") or data.get("parentId")
    return folder_id, name, parent_id

# Find the 'Files' folder and check 4_Design's parent
files_folder_id = None
design_4_parent_id = None

for folder in all_folders:
    fid, name, parent = get_folder_info(folder)
    if name == 'Files':
        files_folder_id = fid
        print(f"'Files' folder ID: {fid}")
        print(f"'Files' parent ID: {parent}")
    if name == '4_Design':
        design_4_parent_id = parent
        print(f"'4_Design' folder ID: {fid}")
        print(f"'4_Design' parent ID: {parent}")

if files_folder_id == design_4_parent_id:
    print(f"\n✓ '4_Design' IS a child of 'Files'")
    print(f"  Use path: Files/Files/4_Design/...")
else:
    print(f"\n✗ '4_Design' is NOT a direct child of 'Files'")
    print(f"  '4_Design' parent: {design_4_parent_id}")
    # Find what folder has this ID
    for folder in all_folders:
        fid, name, parent = get_folder_info(folder)
        if fid == design_4_parent_id:
            print(f"  Parent folder name: {name}")

In [ ]:
# Debug: Check folder IDs and hierarchy
def get_folder_info(folder):
    data = folder if isinstance(folder, dict) else folder.model_dump(by_alias=True)
    data = data.get("data", data)
    folder_id = data.get("folderId") or data.get("id")
    name = data.get("folderName") or data.get("name")
    parent_id = data.get("parentFolderId") or data.get("parentId")
    return folder_id, name, parent_id

# Find the 'Files' folder and check 4_Design's parent
files_folder_id = None
design_4_parent_id = None

for folder in all_folders:
    fid, name, parent = get_folder_info(folder)
    if name == 'Files':
        files_folder_id = fid
        print(f"'Files' folder ID: {fid}")
        print(f"'Files' parent ID: {parent}")
    if name == '4_Design':
        design_4_parent_id = parent
        print(f"'4_Design' folder ID: {fid}")
        print(f"'4_Design' parent ID: {parent}")

if files_folder_id == design_4_parent_id:
    print(f"\n✓ '4_Design' IS a child of 'Files'")
    print(f"  Use path: Files/Files/4_Design/...")
else:
    print(f"\n✗ '4_Design' is NOT a direct child of 'Files'")
    print(f"  '4_Design' parent: {design_4_parent_id}")
    # Find what folder has this ID
    for folder in all_folders:
        fid, name, parent = get_folder_info(folder)
        if fid == design_4_parent_id:
            print(f"  Parent folder name: {name}")

In [ ]:
files = [
    "list of file paths here"
    ]

# Alternative way to download files using a list of file paths

if len(files) == 0:
    print("⚠️  No files found to download. Please check the file paths and try again.")
else:
    downloaded_files = dalux.files.bulk_download_files(
        files=files,
        save_metadata=True,
        verbose=True, 
        save_path="outputs/",
        save_historically=True,
    )

In [ ]:
FILE_AREA_ID = file_areas[0].file_area_id  # You need to provide a valid file_area_id
dalux.set_default_file_area(FILE_AREA_ID)
FILE_AREA_ID

In [ ]:
from dalux_build.models import FileNameFilter

filters = FileNameFilter(
    contains=["K00_T99"],  # Molio model's name convention
    extensions=[".ifc"]
)

dalux.files.bulk_download_folder(
    "Files/Files/4_Design/C07_Geometry/C07.05_BIM",
    save_path="outputs",
    filters=filters,
    verbose=True
)

In [ ]:
from dalux_build.models import FileNameFilter

filters = FileNameFilter(
    contains=["K00_T99"], # Molio model's name convention
    extensions=[".ifc"]
)

dalux.files.bulk_download_folder(
    "Files/4_Design/C07_Geometry/C07.05_BIM",
    save_path="outputs",
    filters=filters,
    verbose=True
)